name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.3'

    - name: gofmt
      run: ! gofmt -s -d . | grep '^'

    - name: staticcheck
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"