name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
		name: "Run CI"
		runs-on: ubuntu-latest
		steps:
		- uses: actions/checkout@v1
			with:
			fetch-depth: 1

		- uses: actions/setup-go@v4
			with:
				go-version: '>=1.20.3'
		- run: ! gofmt -s -d . | grep '^'

		- uses: dominikh/staticcheck-action@v1.2.0
			with:
			version: "2022.1.1"